<?php
/**
 * PEAR_PackageUpdate Package Script Generator
 *
 * Generate a new fresh version of package xml 2.0
 * built with PEAR_PackageFileManager 1.6.0+
 *
 * PHP versions 4 and 5
 *
 * LICENSE: This source file is subject to version 3.01 of the PHP license
 * that is available through the world-wide-web at the following URI:
 * http://www.php.net/license/3_01.txt.  If you did not receive a copy of
 * the PHP License and are unable to obtain it through the web, please
 * send a note to license@php.net so we can mail you a copy immediately.
 *
 * @category  PEAR
 * @package   PEAR_PackageUpdate
 * @author    Laurent Laville <pear@laurent-laville.org>
 * @copyright 2007-2009 Laurent Laville
 * @license   http://www.php.net/license/3_01.txt  PHP License 3.01
 * @version   CVS: $Id$
 * @link      http://pear.php.net/package/PEAR_PackageUpdate
 * @since     File available since Release 0.6.0
 * @ignore
 */

require_once 'PEAR/PackageFileManager2.php';

PEAR::setErrorHandling(PEAR_ERROR_DIE);

$packagefile = 'c:/php/pear/PEAR_PackageUpdate/package2.xml';

$options = array('filelistgenerator' => 'cvs',
    'packagefile' => 'package2.xml',
    'baseinstalldir' => 'PEAR',
    'addhiddenfiles' => true,
    'simpleoutput' => true,
    'clearcontents' => false,
    'changelogoldtonew' => false,
    'ignore' => array(__FILE__)
    );

$p2 = &PEAR_PackageFileManager2::importOptions($packagefile, $options);
$p2->setPackageType('php');
$p2->addRelease();
$p2->setReleaseVersion('1.1.0a1');
$p2->setAPIVersion('1.1.0');
$p2->setReleaseStability('alpha');
$p2->setAPIStability('alpha');
$p2->setNotes('
WARNING: As pear channel did not provided anymore XMLRPC support,
I have not tested the XmlRPC adapter on real server. Tests and feedback are welcome!

[+] New features
- introduce adapter interface to communicate with channel remote server (credits to avb)

[*] Improvements / changes
- with adapters you may now try many protocols (on same call) to check updates
  see test suite PEAR_PackageUpdate_TestSuite_Stub, testCheckUpdateWithSoapOrREST
  as example

[-] Bugfixes
- fix notice error (on unserialize data) when preference file is corrupted
- fix notice error when asking update for a package not yet installed
- add missing error level when pushing some error on stack
- fix error content generated by abstract methods
- fix notice error into getInstalledRelease() when call for package that is not installed

[!] Quality Assurance
- update unit test suites (for PHPUnit 3.2+) with code coverage closest to 100% (84.82)
- fix E_STRICT error
');
$p2->addInstallAs('Cli.php', 'PackageUpdate/Cli.php');
$p2->generateContents();

//$p2->setPearinstallerDep('1.5.4');
/*$p2->updateMaintainer('lead', 'scottmattocks',
                      'Scott Mattocks', 'scottmattocks@php.net', 'no'); */

if (isset($_GET['make'])
    || (isset($_SERVER['argv']) && @$_SERVER['argv'][1] == 'make')) {
    $p2->writePackageFile();
} else {
    $p2->debugPackageFile();
}
?>